/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaCliente;
//@utor omar aexander gonzalez agip

import ListasAux.ListaEnlazada;
import capaDatos.listaGrupos;
import capaNegocio.Grupo;
import capaNegocio.ReportesMatricula;
import java.util.Calendar;
import java.util.Date;

import javax.swing.DefaultComboBoxModel;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;


public class frmRegistrarGrupo2 extends javax.swing.JDialog {

    private int codPrograma = -1;

    public frmRegistrarGrupo2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        listaGrupos.obtenerLista();
        this.setTitle("Registro de Grupos");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDNI = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cboPrograma = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cboNivel = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboModalidad = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblLibro = new javax.swing.JLabel();
        buttonAero1 = new org.edisoncor.gui.button.ButtonAero();
        jLabel6 = new javax.swing.JLabel();
        cboHorario = new javax.swing.JComboBox<>();
        buttonAero2 = new org.edisoncor.gui.button.ButtonAero();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrupos = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        cboNivel1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cboModalidad1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboHorario1 = new javax.swing.JComboBox<>();
        lblNivel = new javax.swing.JLabel();
        lblModalidad = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        buttonAero4 = new org.edisoncor.gui.button.ButtonAero();
        jLabel15 = new javax.swing.JLabel();
        lblPrograma1 = new javax.swing.JLabel();
        buttonAero5 = new org.edisoncor.gui.button.ButtonAero();
        lblHorario = new javax.swing.JLabel();
        buttonAero3 = new org.edisoncor.gui.button.ButtonAero();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        fechaFin = new com.toedter.calendar.JDateChooser();

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 187, 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Programa:");

        cboPrograma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Niños", "Adolecentes", "Adultos" }));
        cboPrograma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboProgramaItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nivel:");

        cboNivel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNivelItemStateChanged(evt);
            }
        });
        cboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNivelActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Modalidad:");

        cboModalidad.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboModalidadItemStateChanged(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Fecha de inicio:");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Libros:");

        lblLibro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblLibro.setText("_");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonAero1.setBackground(new java.awt.Color(1, 0, 1));
        buttonAero1.setText("Crear");
        buttonAero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Horario:");

        cboHorario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHorarioItemStateChanged(evt);
            }
        });

        buttonAero2.setBackground(new java.awt.Color(1, 0, 1));
        buttonAero2.setText("Mostrar grupos");
        buttonAero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero2ActionPerformed(evt);
            }
        });

        tblGrupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGruposMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGrupos);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nivel:");

        cboNivel1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNivel1ItemStateChanged(evt);
            }
        });
        cboNivel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNivel1ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Modalidad:");

        cboModalidad1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboModalidad1ItemStateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Horario:");

        cboHorario1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboHorario1ItemStateChanged(evt);
            }
        });

        lblNivel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNivel.setText("_");

        lblModalidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblModalidad.setText("_");

        jLabel12.setText("modificar a");

        jLabel13.setText("modificar a");

        jLabel14.setText("modificar a");

        buttonAero4.setBackground(new java.awt.Color(1, 0, 1));
        buttonAero4.setText("Modificar");
        buttonAero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero4ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Programa:");

        lblPrograma1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrograma1.setText("_");
        lblPrograma1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                lblPrograma1ComponentAdded(evt);
            }
        });
        lblPrograma1.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                lblPrograma1HierarchyChanged(evt);
            }
        });
        lblPrograma1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblPrograma1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        buttonAero5.setBackground(new java.awt.Color(1, 0, 1));
        buttonAero5.setText("Eliminar");
        buttonAero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero5ActionPerformed(evt);
            }
        });

        lblHorario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblHorario.setText("_");

        buttonAero3.setBackground(new java.awt.Color(1, 0, 1));
        buttonAero3.setText("Comprobar");
        buttonAero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAero3ActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Registro de Grupos");

        jLabel1.setText("precio total:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Fecha de finilización:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cboPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(buttonAero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPrecio)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(buttonAero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181)
                                .addComponent(buttonAero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(290, 290, 290)
                                .addComponent(buttonAero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModalidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(41, 41, 41)
                                    .addComponent(lblHorario, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cboModalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cboNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addGap(18, 18, 18)
                                            .addComponent(cboHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(18, 18, 18)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(163, 163, 163)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonAero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(cboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrograma1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboNivel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13)
                                .addComponent(cboModalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(cboHorario1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAero4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonAero5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void cboHorario1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHorario1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboHorario1ItemStateChanged

    private void cboModalidad1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboModalidad1ItemStateChanged
        if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Regular")) {
            cboHorario1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Lunes a jueves(8:00 am-10:00 am)", "Lunes a jueves(04:00 pm-06:00 pm)", "Lunes a jueves(06:15 pm-8:15 pm)", "Lunes a jueves(08:30 pm-10:30 pm)"}));
        } else if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Regular fines de semana")) {
            cboHorario1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Viernes(4:00 pm-8:00 pm)", "Sabado(9:00 am-1:00 pm)"}));
        } else if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Intensivo")) {
            cboHorario1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Viernes(4:00 pm-8:00 pm)", "Sabado(9:00 am-1:00 pm)"}));
        } else if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Intensivo fines de semana")) {
            cboHorario.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Sabado(4:00 pm-8:00 pm) y domingo(9:00 am-1:00 pm)"}));
        }
    }//GEN-LAST:event_cboModalidad1ItemStateChanged

    private void cboNivel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNivel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNivel1ActionPerformed

    private void cboNivel1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNivel1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNivel1ItemStateChanged

    public void tabla() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("PROGRAMA");
        modelo.addColumn("NIVEL");
        modelo.addColumn("MODALIDAD");
        modelo.addColumn("LIBROS");
        modelo.addColumn("HORARIO");
        modelo.addColumn("FECHA I");
        modelo.addColumn("FECHA F");
        ListaEnlazada lista;
        lista = Grupo.consultarTodo();
        Grupo grup;

        Object datos[] = new Object[8];

        for (int i = 0; i < lista.tamaño(); i++) {
            grup = (Grupo) lista.Buscar(i);
            datos[0] = grup.getIdGrupo();
            datos[1] = grup.getPrograma();
            datos[2] = grup.getNivel();
            datos[3] = grup.getModalidad();
            datos[4] = grup.getLibro();
            datos[5] = grup.getHorario();
            datos[6] = grup.getFechaInicio();
            datos[7] = grup.getFechaFin();
            modelo.addRow(datos);
        }
        tblGrupos.setModel(modelo);
    }

    private void buttonAero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero2ActionPerformed
        tabla();
        //tblGrupos.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    }//GEN-LAST:event_buttonAero2ActionPerformed

    private void cboHorarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboHorarioItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cboHorarioItemStateChanged

    private void buttonAero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero1ActionPerformed
 
        java.util.Date datoFecha = fecha.getDate();
        java.util.Date fechaFinal = fechaFin.getDate();
        long mil2 = fechaFinal.getTime();
        long mil = datoFecha.getTime();
        java.sql.Date fecha = new java.sql.Date(mil);
        java.sql.Date fechaFin = new java.sql.Date(mil2);
        //***********************comprobar  que el rango de fechas no sobrepasa los 3 meses
        java.util.List<Date> listaFechas = ReportesMatricula.getIntervaloFechas(fecha, fechaFin, Calendar.MONTH);
        if (listaFechas.size() > 3) {
            JOptionPane.showMessageDialog(null, "El grupo sobrepasa los 3 meses");
            return;
        }
        Grupo obj = new Grupo();

        int idGrupo = Grupo.generarIdGrupo();
        //if(pos==-1){
        obj.setIdGrupo(idGrupo + 1);
        obj.setPrograma(cboPrograma.getSelectedItem().toString());
        obj.setNivel(cboNivel.getSelectedItem().toString());
        obj.setModalidad(cboModalidad.getSelectedItem().toString());
        obj.setHorario(cboHorario.getSelectedItem().toString());
        obj.setPrecioTotal(Float.parseFloat(txtPrecio.getText()));

        obj.setLibro(lblLibro.getText());
        obj.setFechaInicio(fecha);
        obj.setFechaFin(fechaFin);
        listaGrupos.adicionar(obj);
        listaGrupos.GuardarLista();
        JOptionPane.showMessageDialog(null, "Nuevo grupo creado satisfactoriamente");
        // }else
        //  JOptionPane.showMessageDialog(null, "Numero de item ya en uso por otro grupo, ingrese un item diferente");
        //  txtId.setText("");
        lblLibro.setText("");
        cboPrograma.setSelectedIndex(0);
        cboNivel.setSelectedIndex(0);
        cboModalidad.setSelectedIndex(0);
        cboHorario.setSelectedIndex(0);

    }//GEN-LAST:event_buttonAero1ActionPerformed

    private void cboModalidadItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboModalidadItemStateChanged

        if (cboModalidad.getSelectedItem().toString().equalsIgnoreCase("Regular")) {
            cboHorario.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Lunes a jueves(8:00 am-10:00 am)", "Lunes a jueves(04:00 pm-06:00 pm)", "Lunes a jueves(06:15 pm-8:15 pm)", "Lunes a jueves(08:30 pm-10:30 pm)"}));
        } else if (cboModalidad.getSelectedItem().toString().equalsIgnoreCase("Regular fines de semana")) {
            cboHorario.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Viernes(4:00 pm-8:00 pm)", "Sabado(9:00 am-1:00 pm)"}));
        } else if (cboModalidad.getSelectedItem().toString().equalsIgnoreCase("Intensivo")) {
            cboHorario.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Viernes(4:00 pm-8:00 pm)", "Sabado(9:00 am-1:00 pm)"}));
        } else if (cboModalidad.getSelectedItem().toString().equalsIgnoreCase("Intensivo fines de semana")) {
            cboHorario.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Sabado(4:00 pm-8:00 pm) y domingo(9:00 am-1:00 pm)"}));
        }
    }//GEN-LAST:event_cboModalidadItemStateChanged

    private void cboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNivelActionPerformed

    private void cboNivelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNivelItemStateChanged
        if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Kinder")) {
            lblLibro.setText("<html>-Toy Box 1<p>-Toy Box 2");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Pre Kids")) {
            lblLibro.setText("<html>-Show and Tell 3");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Kids")) {
            lblLibro.setText("<html>-Big English Starter<p>-Big English 2<p>-Big English 3");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Children")) {
            lblLibro.setText("<html>-Oxfor Discover 1<p>-Oxfor Discover 2<p>-Oxfor Discover 3");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Beginner-A1")) {
            lblLibro.setText("<html>-Touchstone 1");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Elementary-A2")) {
            lblLibro.setText("<html>-Touchstone 2");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Pre Intermediate-B1")) {
            lblLibro.setText("<html>-Touchstone 3");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Intermediate-B2")) {
            lblLibro.setText("<html>-Touchstone 4");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Upper Intermediate-C1")) {
            lblLibro.setText("<html>-Viewpoint 1");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Advanced C2")) {
            lblLibro.setText("<html>-Viewpoint 2");
        } else if (cboNivel.getSelectedItem().toString().equalsIgnoreCase("Adolecentes")) {
            lblLibro.setText("<html>-Live Beat 1<p>-Live Beat 2");
        } else {
            lblLibro.setText("_");
        }

    }//GEN-LAST:event_cboNivelItemStateChanged

    private void cboProgramaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboProgramaItemStateChanged
        //Nivel
        if (cboPrograma.getSelectedItem().toString().equalsIgnoreCase("Niños")) {
            cboNivel.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "kinder", "pre kids", "kids", "children"}));
        } else if (cboPrograma.getSelectedItem().toString().equalsIgnoreCase("Adolecentes")) {
            cboNivel.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Adolecentes"}));
        } else if (cboPrograma.getSelectedItem().toString().equalsIgnoreCase("Adultos")) {
            cboNivel.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Beginner-A1", "Elementary-A2", "Pre Intermediate-B1", "Intermediate-B2", "Upper Intermediate-C1", "Advanced C2"}));
        }
        //Modalidad:
        if (cboPrograma.getSelectedItem().toString().equalsIgnoreCase("Niños")) {
            cboModalidad.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Regular"}));
        } else if (cboPrograma.getSelectedItem().toString().equalsIgnoreCase("Adolecentes")) {
            cboModalidad.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Regular", "Intensivo"}));

        } else if (cboPrograma.getSelectedItem().toString().equalsIgnoreCase("Adultos")) {
            cboModalidad.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Regular", "Regular fines de semana", "Intensivo", "Intensivo fines de semana"}));
        }
    }//GEN-LAST:event_cboProgramaItemStateChanged

    private void tblGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGruposMouseClicked
        int Fila = tblGrupos.getSelectedRow();
        codPrograma = Integer.parseInt(tblGrupos.getValueAt(Fila, 0).toString());
        lblPrograma1.setText(tblGrupos.getValueAt(Fila, 1).toString());
        lblNivel.setText(tblGrupos.getValueAt(Fila, 2).toString());
        lblModalidad.setText(tblGrupos.getValueAt(Fila, 3).toString());
        lblHorario.setText(tblGrupos.getValueAt(Fila, 5).toString());
    }//GEN-LAST:event_tblGruposMouseClicked

    private void lblPrograma1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblPrograma1AncestorAdded


    }//GEN-LAST:event_lblPrograma1AncestorAdded

    private void lblPrograma1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_lblPrograma1ComponentAdded

    }//GEN-LAST:event_lblPrograma1ComponentAdded

    private void lblPrograma1HierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_lblPrograma1HierarchyChanged

    }//GEN-LAST:event_lblPrograma1HierarchyChanged

    private void buttonAero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero3ActionPerformed
        //combos
        //niveles
        if (lblPrograma1.getText().equalsIgnoreCase("Niños")) {
            cboNivel1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "kinder", "pre kids", "kids", "children"}));
        } else if (lblPrograma1.getText().equalsIgnoreCase("Adolecentes")) {
            cboNivel1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Adolecentes"}));
        } else if (lblPrograma1.getText().equalsIgnoreCase("Adultos")) {
            cboNivel1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Beginner-A1", "Elementary-A2", "Pre Intermediate-B1", "Intermediate-B2", "Upper Intermediate-C1", "Advanced C2"}));
        }
        //Modalidad:
        if (lblPrograma1.getText().equalsIgnoreCase("Niños")) {
            cboModalidad1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Regular"}));
        } else if (lblPrograma1.getText().equalsIgnoreCase("Adolecentes")) {
            cboModalidad1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Regular", "Intensivo"}));

        } else if (lblPrograma1.getText().equalsIgnoreCase("Adultos")) {
            cboModalidad1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Regular", "Regular fines de semana", "Intensivo", "Intensivo fines de semana"}));
        }

        //Horarios
        if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Regular")) {
            cboHorario1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Lunes a jueves(8:00 am-10:00 am)", "Lunes a jueves(04:00 pm-06:00 pm)", "Lunes a jueves(06:15 pm-8:15 pm)", "Lunes a jueves(08:30 pm-10:30 pm)"}));
        } else if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Regular fines de semana")) {
            cboHorario1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Viernes(4:00 pm-8:00 pm)", "Sabado(9:00 am-1:00 pm)"}));
        } else if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Intensivo")) {
            cboHorario1.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Viernes(4:00 pm-8:00 pm)", "Sabado(9:00 am-1:00 pm)"}));
        } else if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Intensivo fines de semana")) {
            cboHorario.setModel(new DefaultComboBoxModel<>(new String[]{"Seleccione", "Sabado(4:00 pm-8:00 pm) y domingo(9:00 am-1:00 pm)"}));
        }
    }//GEN-LAST:event_buttonAero3ActionPerformed

    private void buttonAero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero5ActionPerformed
        if (codPrograma == -1) {
            JOptionPane.showMessageDialog(null, "no se ha seleccionado un item");
            return;
        }
        Grupo.eliminarGrupo(codPrograma);

        JOptionPane.showMessageDialog(null, "Eliminación correcta");
        tabla();
    }//GEN-LAST:event_buttonAero5ActionPerformed

    private void buttonAero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAero4ActionPerformed
        if (codPrograma == -1) {
            return;
        }
        int Fila = tblGrupos.getSelectedRow();
        String id = tblGrupos.getValueAt(Fila, 0).toString();
        String programa = tblGrupos.getValueAt(Fila, 1).toString();
        String libros = tblGrupos.getValueAt(Fila, 4).toString();
        String fechaI = tblGrupos.getValueAt(Fila, 6).toString();

        String nivel, modalidad, horario;
        if (cboNivel1.getSelectedItem().toString().equalsIgnoreCase("Seleccione")) {
            nivel = lblNivel.getText();
        } else {
            nivel = cboNivel1.getSelectedItem().toString();
        }

        if (cboModalidad1.getSelectedItem().toString().equalsIgnoreCase("Seleccione")) {
            modalidad = lblModalidad.getText();
        } else {
            modalidad = cboModalidad1.getSelectedItem().toString();
        }

        if (cboHorario1.getSelectedItem().toString().equalsIgnoreCase("Seleccione") || cboHorario1 == null) {
            horario = lblHorario.getText();
        } else {
            horario = cboHorario1.getSelectedItem().toString();
        }

        Grupo grup = new Grupo();
        grup.setNivel(nivel);
        grup.setModalidad(modalidad);
        grup.setHorario(horario);
        grup.setIdGrupo(codPrograma);
        grup.setPrograma(programa);
        grup.setLibro(libros);
        // grup.setFechaInicio(fechaI);
        Grupo.ModificarGrupo(grup, codPrograma);
        JOptionPane.showMessageDialog(null, "Grupo modificado exitosamente");
        tabla();
    }//GEN-LAST:event_buttonAero4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarGrupo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarGrupo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarGrupo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarGrupo2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmRegistrarGrupo2 dialog = new frmRegistrarGrupo2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonAero buttonAero1;
    private org.edisoncor.gui.button.ButtonAero buttonAero2;
    private org.edisoncor.gui.button.ButtonAero buttonAero3;
    private org.edisoncor.gui.button.ButtonAero buttonAero4;
    private org.edisoncor.gui.button.ButtonAero buttonAero5;
    private javax.swing.JComboBox<String> cboHorario;
    private javax.swing.JComboBox<String> cboHorario1;
    private javax.swing.JComboBox<String> cboModalidad;
    private javax.swing.JComboBox<String> cboModalidad1;
    private javax.swing.JComboBox<String> cboNivel;
    private javax.swing.JComboBox<String> cboNivel1;
    private javax.swing.JComboBox<String> cboPrograma;
    private com.toedter.calendar.JDateChooser fecha;
    private com.toedter.calendar.JDateChooser fechaFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblLibro;
    private javax.swing.JLabel lblModalidad;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblPrograma1;
    private javax.swing.JTable tblGrupos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
